// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmk-pY3P0TnLMQdPB-NURr6pfqwSVAaI',
    appId: '1:160464927502:web:1482c1154ce1fb173a755f',
    messagingSenderId: '160464927502',
    projectId: 'flutter-firestore-da15a',
    authDomain: 'flutter-firestore-da15a.firebaseapp.com',
    storageBucket: 'flutter-firestore-da15a.firebasestorage.app',
    measurementId: 'G-G7D9Q40YDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hxnYNYq2GnglarmrM1j53r33e9Nyu94',
    appId: '1:160464927502:android:2f4138acda8102de3a755f',
    messagingSenderId: '160464927502',
    projectId: 'flutter-firestore-da15a',
    storageBucket: 'flutter-firestore-da15a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCta6l5_3fVZtvakiatCIbriOGPEcsTBxA',
    appId: '1:160464927502:ios:9bbc02d4270b38cf3a755f',
    messagingSenderId: '160464927502',
    projectId: 'flutter-firestore-da15a',
    storageBucket: 'flutter-firestore-da15a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCta6l5_3fVZtvakiatCIbriOGPEcsTBxA',
    appId: '1:160464927502:ios:9bbc02d4270b38cf3a755f',
    messagingSenderId: '160464927502',
    projectId: 'flutter-firestore-da15a',
    storageBucket: 'flutter-firestore-da15a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYmk-pY3P0TnLMQdPB-NURr6pfqwSVAaI',
    appId: '1:160464927502:web:b0f664920a622bea3a755f',
    messagingSenderId: '160464927502',
    projectId: 'flutter-firestore-da15a',
    authDomain: 'flutter-firestore-da15a.firebaseapp.com',
    storageBucket: 'flutter-firestore-da15a.firebasestorage.app',
    measurementId: 'G-T247XHLLEK',
  );
}
